version: '3.8'

services:
  app:
    build: .
    container_name: markov_brain_app
    ports:
      - "8000:8000"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - TARGET_WS_URL=wss://vip.ee8833.me/ws/?token=1_362202_1783008583_af4a03bef6054116d973ca32da948b69&x-device=pc
      - MAX_HISTORY_SIZE=10000
    depends_on:
      - redis
    restart: always

  redis:
    image: redis:alpine
    container_name: markov_brain_redis
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data
    restart: always

volumes:
  redis_data:
